export {
	CARET,
	EditorRoot,
	EditorContent,
	EditorBlock,
	InlineContent,
	EditorCaretOverlay,
	EditorBlockHandle,
	EditorDragOverlay,
	EditorRegionSelector,
	EditorSelectionRect,
	EditorFieldEditor,
} from "./editor/index";

export {
	ToolbarRoot,
	ToolbarGroup,
	ToolbarButton,
	ToolbarToggle,
	ToolbarSelect,
	ToolbarSeparator,
} from "./toolbar/index";

export {
	SlashMenuRoot,
	SlashMenuContent,
	SlashMenuInput,
	SlashMenuList,
	SlashMenuGroup,
	SlashMenuItem,
	SlashMenuEmpty,
} from "./slash-menu/index";

export {
	SelectionToolbarRoot,
	SelectionToolbarContent,
} from "./selection-toolbar/index";

export {
	SearchRoot,
	SearchInput,
	SearchResults,
	SearchNext,
	SearchPrevious,
	SearchReplaceInput,
	SearchReplace,
	SearchReplaceAll,
	SearchCaseSensitive,
	SearchRegExpToggle,
	SearchWholeWord,
} from "./search/index";

export {
	AIRoot,
	AITrigger,
	AISelectionTrigger,
	AICommandMenu,
	AICommandInput,
	AICommandList,
	AICommandItem,
	AIGenerationZone,
	AIStructuredTargetPreview,
	AIActionBar,
	AIAcceptButton,
	AIRejectButton,
	AIRetryButton,
	AISuggestion,
	AITrackChanges,
	AIDiffView,
	AIChangeList,
	AIProgress,
	AIToolStream,
	AIContextualPromptTrigger,
	AIContextualPromptSurface,
	AIContextualPromptComposer,
	AIInlineSuggestionControls,
	AIInlineSuggestionFloatingSurface,
	AIInlineSuggestionCount,
	AIInlineSuggestionPreviousButton,
	AIInlineSuggestionNextButton,
	AIInlineSuggestionAcceptButton,
	AIInlineSuggestionRejectButton,
	AIInlineSession,
	AIInlineSessionActions,
} from "./ai/index";
export { AISuggestionsRoot, AISuggestionsPopover } from "./aiSuggestions/index";
export {
	MultiplayerPresenceList,
	MultiplayerRemoteCursors,
	MultiplayerCaretOverlay,
} from "./multiplayer/index";

// ── Pen.* namespace for compound component API ──────────────

import {
	CARET,
	EditorRoot,
	EditorContent,
	EditorBlock,
	InlineContent,
	EditorCaretOverlay,
	EditorBlockHandle,
	EditorDragOverlay,
	EditorRegionSelector,
	EditorSelectionRect,
	EditorFieldEditor,
} from "./editor/index";

import {
	ToolbarRoot,
	ToolbarGroup,
	ToolbarButton,
	ToolbarToggle,
	ToolbarSelect,
	ToolbarSeparator,
} from "./toolbar/index";

import {
	SlashMenuRoot,
	SlashMenuContent,
	SlashMenuInput,
	SlashMenuList,
	SlashMenuGroup,
	SlashMenuItem,
	SlashMenuEmpty,
} from "./slash-menu/index";

import {
	SelectionToolbarRoot,
	SelectionToolbarContent,
} from "./selection-toolbar/index";

import {
	SearchRoot,
	SearchInput,
	SearchResults,
	SearchNext,
	SearchPrevious,
	SearchReplaceInput,
	SearchReplace,
	SearchReplaceAll,
	SearchCaseSensitive,
	SearchRegExpToggle,
	SearchWholeWord,
} from "./search/index";

import {
	AIRoot,
	AITrigger,
	AISelectionTrigger,
	AICommandMenu,
	AICommandInput,
	AICommandList,
	AICommandItem,
	AIGenerationZone,
	AIStructuredTargetPreview,
	AIActionBar,
	AIAcceptButton,
	AIRejectButton,
	AIRetryButton,
	AISuggestion,
	AITrackChanges,
	AIDiffView,
	AIChangeList,
	AIProgress,
	AIToolStream,
	AIContextualPromptTrigger,
	AIContextualPromptSurface,
	AIContextualPromptComposer,
	AIInlineSuggestionControls,
	AIInlineSuggestionFloatingSurface,
	AIInlineSuggestionCount,
	AIInlineSuggestionPreviousButton,
	AIInlineSuggestionNextButton,
	AIInlineSuggestionAcceptButton,
	AIInlineSuggestionRejectButton,
	AIInlineSession,
	AIInlineSessionActions,
} from "./ai/index";
import { AISuggestionsRoot, AISuggestionsPopover } from "./aiSuggestions/index";
import {
	MultiplayerPresenceList,
	MultiplayerRemoteCursors,
	MultiplayerCaretOverlay,
} from "./multiplayer/index";

export const Pen = {
	Editor: {
		Root: EditorRoot,
		Content: EditorContent,
		Block: EditorBlock,
		InlineContent,
		CaretOverlay: EditorCaretOverlay,
		CARET,
		BlockHandle: EditorBlockHandle,
		DragOverlay: EditorDragOverlay,
		RegionSelector: EditorRegionSelector,
		SelectionRect: EditorSelectionRect,
		FieldEditor: EditorFieldEditor,
	},
	Toolbar: {
		Root: ToolbarRoot,
		Group: ToolbarGroup,
		Button: ToolbarButton,
		Toggle: ToolbarToggle,
		Select: ToolbarSelect,
		Separator: ToolbarSeparator,
	},
	SlashMenu: {
		Root: SlashMenuRoot,
		Content: SlashMenuContent,
		Input: SlashMenuInput,
		List: SlashMenuList,
		Group: SlashMenuGroup,
		Item: SlashMenuItem,
		Empty: SlashMenuEmpty,
	},
	SelectionToolbar: {
		Root: SelectionToolbarRoot,
		Content: SelectionToolbarContent,
	},
	Search: {
		Root: SearchRoot,
		Input: SearchInput,
		Results: SearchResults,
		Next: SearchNext,
		Previous: SearchPrevious,
		ReplaceInput: SearchReplaceInput,
		Replace: SearchReplace,
		ReplaceAll: SearchReplaceAll,
		CaseSensitive: SearchCaseSensitive,
		RegExp: SearchRegExpToggle,
		WholeWord: SearchWholeWord,
	},
	AI: {
		Root: AIRoot,
		Trigger: AITrigger,
		SelectionTrigger: AISelectionTrigger,
		CommandMenu: AICommandMenu,
		CommandInput: AICommandInput,
		CommandList: AICommandList,
		CommandItem: AICommandItem,
		GenerationZone: AIGenerationZone,
		StructuredTargetPreview: AIStructuredTargetPreview,
		ActionBar: AIActionBar,
		Accept: AIAcceptButton,
		Reject: AIRejectButton,
		Retry: AIRetryButton,
		Suggestion: AISuggestion,
		TrackChanges: AITrackChanges,
		DiffView: AIDiffView,
		ChangeList: AIChangeList,
		Progress: AIProgress,
		ToolStream: AIToolStream,
		ContextualPromptTrigger: AIContextualPromptTrigger,
		ContextualPromptSurface: AIContextualPromptSurface,
		ContextualPromptComposer: AIContextualPromptComposer,
		InlineSuggestionControls: AIInlineSuggestionControls,
		InlineSuggestionFloatingSurface: AIInlineSuggestionFloatingSurface,
		InlineSuggestionCount: AIInlineSuggestionCount,
		InlineSuggestionPrevious: AIInlineSuggestionPreviousButton,
		InlineSuggestionNext: AIInlineSuggestionNextButton,
		InlineSuggestionAccept: AIInlineSuggestionAcceptButton,
		InlineSuggestionReject: AIInlineSuggestionRejectButton,
		InlineSession: AIInlineSession,
		InlineSessionActions: AIInlineSessionActions,
	},
	AISuggestions: {
		Root: AISuggestionsRoot,
		Popover: AISuggestionsPopover,
	},
	Multiplayer: {
		PresenceList: MultiplayerPresenceList,
		RemoteCursors: MultiplayerRemoteCursors,
		CaretOverlay: MultiplayerCaretOverlay,
	},
} as const;
